### ISSUE TITLE
Link to User Stories in Issue Tracker

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#102]
Since the user stories are all in your issue tracker, it would be cool if you could link to them from the use cases wiki page.

**Comment by lolicatgirls** [comment]
Inkscape is giving me trouble loading up so I will begin working on this while I wait

**Comment by lolicatgirls** [comment]
I have added links to the use cases in test code will now link issues to wiki

**Comment by lolicatgirls** [comment]
Added links and description to wiki use cases, May need to pull up a list and check all the cases are there

**Comment by bkhunter** [comment]
Looks good to me, cleaned up the wiki page as well
