### ISSUE TITLE
Change to assertEquals

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#103]
Please use assertEquals("x and y", x, y) instead of assertTrue("x and y", x == y) In general, use the most specific assert you can, because this will give you the most useful error messages when your test fails. Plus it is a bit more self-documenting

**Comment by eorodrig** [comment]
Went through all the JUnit classes and fixed all inappropriate asserts.

Changed AssertTrue( ****, XX == null) to: AssertNull(*****, XX)
Changed AssertTrue( ****, XX != null) to: AssertNotNull(*****, XX)

Changed AssertTrue( ****, XX == YY) to: AssertEquals(*****, YY, XX)
Changed AssertTrue( ****, XX != YY) to: AssertNotSame(*****, YY, XX)
