### ISSUE TITLE
UML class diagram for project three

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#11]
This will describe the code base for the application

**Comment by mfritze** [comment]
I modified the UML to reflect what Alex described in the email about the tag manager class, as well as what we discussed on Google+. Let me know what you guys think, and if you want to see any changes.

**Comment by eorodrig** [comment]
can you upload as a pdf?

**Comment by mfritze** [comment]
done. It's draft 2

**Comment by eorodrig** [comment]
can you re-upload? it seems to be an empty PDF

**Comment by mfritze** [comment]
I'm having some trouble getting it to do anything with pdf. Anyone have any ideas?

For now I uploaded it as a png

**Comment by bkhunter** [comment]
I couldn't get the storyboard to show as a PDF...PNG should be fine

**Comment by eorodrig** [comment]
png works for me.

I looked at the UML. what do you guys think of adding some methods to users?

Claimant:
ViewClaims
AddClaims
DeleteClaims
EditClaims

Approver:
ViewClaims

**Comment by bkhunter** [comment]
Would they be methods to start activities? Seems like a good idea, especially for the UML in this stage.

**Comment by eorodrig** [comment]
im not to sure. I think we need some sort of indication of what each user can do. If we can do this through variables, that is another option we can look at.

**Comment by bkhunter** [comment]
Well I think just having the methods for now is a good idea as they indicate functionality. We can figure out how to do it later.

**Comment by bkhunter** [comment]
The UML is up, I think it looks good. I'll close this for now, but everyone should give it a final inspection as I made a few adjustments (claim has a claim status not claim list, and added a tag class to tag manager).
