### ISSUE TITLE
Related issues linked to use cases

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#111]
Your use cases have a spot for open issues, but none of the related issues are linked?

**Comment by bkhunter** [comment]
Anyone know what this means?

**Comment by lolicatgirls** [comment]
Hm, I think this is referring to our "Open Issues" sections in the use case wikis, imo linking the relevant use case should be sufficient, perhaps we can remove this and replicate it by adding a " - open" next to relevant cases
