### ISSUE TITLE
Approver tests

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#124]
Have the approver tests compile.

[Tests](https://github.com/CMPUT301W15T13/TravelPlanner/blob/master/TravelPlannerTest/src/ca/ualberta/cmput301w15t13/test/ApproverTests.java#L95)

This requires the following to exist (but not necessarily work):
- claim class
- claimStatus class
- claim set status  method
- claim getComments method
- claim clearComments method
- claimStatus static variables
- approver class
- approver approveClaim method
- approver addComment method

**Comment by eorodrig** [comment]
Started working on this test.
Will post when done.

Will be using the specified classes:
claim class
claimStatus class
approver class
