### ISSUE TITLE
ClaimTagTests

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#125]
Have the claim tag tests compile

[Tests](https://github.com/CMPUT301W15T13/TravelPlanner/blob/master/TravelPlannerTest/src/ca/ualberta/cmput301w15t13/test/ClaimTagsTest.java)

This requires the following to exist (but not necessarily work):

**These tests may need to be modified to match the model, ie. using ClaimManager class.**

- Claim class
- Claim addTag method
- Claim getTags method
- Claim removeTag method
- Potentially more tag methods (not sure about tag.length)
- ClaimListSingleton implemented
- ClaimListSingleton add claim method
- TagManagerSingleton.getTagList() ??

**Comment by eorodrig** [comment]
Will start on this test.

Will need the following classes open:
Claim
ClaimListSingleton
