### ISSUE TITLE
Claim tests

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#126]
Have the claim tests compile

[Tests](https://github.com/CMPUT301W15T13/TravelPlanner/blob/master/TravelPlannerTest/src/ca/ualberta/cmput301w15t13/test/ClaimTest.java#L166)

This requires the following to exist (but not necessarily work):

**note: may need to change the layout to fit the model.**

- ClaimList class
- ClaimList add method
- ClaimList remove method
- Claim class
- Claim setDescription method
- Claim getUsername method
- Claim get startDate method
- Claim get endDate method
- Claim addTravelDestination method
- Claim numberOfDestinations method
- Claim getTravelDestination method
- Claim setClaimDates method
- Claim setUsername method
- Claim editTravelDestination method
- Claim deleteTravelDestination method

**Comment by eorodrig** [comment]
Did most last night. Will take a 2nd look.
