### ISSUE TITLE
ExpenseClaim Status tests

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#127]
Have the approver tests compile.

[Tests](https://github.com/CMPUT301W15T13/TravelPlanner/blob/master/TravelPlannerTest/src/ca/ualberta/cmput301w15t13/test/ExpenseClaimsStatusesTests.java)

This requires the following to exist (but not necessarily work):

- Claim class
- LoginActivity (?)
- LoginActivity submit method
- Claim getStatus method
- Claim getPermission Method
- Login Activity setUserType method

**Comment by eorodrig** [comment]
Will need the ClaimClass and ClaimStatus classes
