### ISSUE TITLE
Expense Item Overall Test

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#128]
Have the expense item tests (overall) compile

[Tests](https://github.com/CMPUT301W15T13/TravelPlanner/blob/master/TravelPlannerTest/src/ca/ualberta/cmput301w15t13/test/ExpenseItemOverallTest.java)

This requires the following to exist (but not necessarily work):

- Claim class
- Expense Item class
- Claim addExpenseItem method
- Claim getExpenseItems method
- Claim setStatus method
- Claim isEditable method
- Claim getExpenseList method

- Expense Item getDate method
- Expense Item getCategory method
- Expense Item getDescription method
- Expense Item getCurrency method
- Expense Item setCategory method
- Expense item setCurrency method
- Expense Item setIncompletenessIndicator method
- Expense Item removeIncompletenessIndicator method
- Expense item isIncomplete method

**Comment by eorodrig** [comment]
Will need specified classes
