### ISSUE TITLE
Expense item reciept test

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#129]
Have the Expense Item Receipt tests compile

[Tests](https://github.com/CMPUT301W15T13/TravelPlanner/blob/master/TravelPlannerTest/src/ca/ualberta/cmput301w15t13/test/ExpenseRepeiptTest.java)

This requires the following to exist (but not necessarily work):

- Claim class
- Claim addReceipt method
- Claim getReciept method
- Login Activity (?)

**Comment by eorodrig** [comment]
It compiles now.
Needed to change methods to rely on ExpenseItem instead of Claim.
