### ISSUE TITLE
CLass for Claim Items

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#13]
Once again, no user stories, but needed for implementation

**Comment by eorodrig** [comment]
Began to write some of the claim model to deal with basic things = Constructor, variables.

Will continue later on today/tomorrow.

**Comment by eorodrig** [comment]
Added the exceptions specified in the JUnit test (claimTest.java)
Implemented first draft of the code for this class.
Fixed JUnit test so that it compiles.

Will do some Junit Testing and modifications at a later time.

**Comment by eorodrig** [comment]
Use Cases A1 to A4 have been written.
All specified JUnit tests are passing,
