### ISSUE TITLE
ClaimTag Tests Passing

### ISSUE THREAD

**Issue by mfritze** [CMPUT301W15T13/TravelPlanner#139]
make the ClaimTagTests class pass.

**Comment by mfritze** [comment]
What's the rational behind the SortedSet in the Tag class?

**Comment by eorodrig** [comment]
I was not too sure how the tags were being stored when I was ensuring that all the JUnit tests compiled. 

The reason why i chose a SortedSet is that:
    1. Tags should be sorted. This structure automatically sorts them
    2. There should not be any duplicate tags. This structure takes care of this as well.

**Comment by bkhunter** [comment]
working on it
