### ISSUE TITLE
Expense List Implemented

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#14]
Code to implement Use cases/stories, but not attached to anyone specifically

**Comment by jihwan1ua** [comment]
Working on this - Ji Hwan Kim - 2015/02/22 - 16:05

**Comment by jihwan1ua** [comment]
Wrote some basic codes for the ExpenseItemList and will continue working on it later today if possible - Ji Hwan Kim - 2015/02/22 - 16:31
