### ISSUE TITLE
Layouts

### ISSUE THREAD

**Issue by jihwan1ua** [CMPUT301W15T13/TravelPlanner#141]
We are going to need layouts for each class and MVC.
If I'm not mistaken, we only have activity_login.xml as our layout and it has the default layout on creation.

**Comment by mfritze** [comment]
I just added some new layouts, fragment layouts,  as well as the new android action bar layout. Can you guys take a look and give some feedback?
For whatever reason I chose to make it a dark theme, but changing it to light is as easy as changing two hex values in the colors.xml file. But you know... if you don't like my design choices I'll probably be heart-broken.
