### ISSUE TITLE
Organize Repository

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#143]
Alex said we have some strange organization, particularly with our MVC folders. We need to go through and find the logical place layout for our code.

From the feedback: 
- not sure that ClaimDateSorter should be in the Controllers package. Maybe Models
- ClaimListSingleton should probably be a model, too
- a few things in surprising places. If you want to use folders like that, which is nice, be careful not to put things where they don't belong. You can always have classes that aren't in one of the MVC folders.

**Comment by eorodrig** [comment]
Claim date sorter can be part of the claim model. Java has quick ways to
sort lists. We can use those.

**Comment by bkhunter** [comment]
Excellent. As long as everything makes sense, we'll be fine I think.
