### ISSUE TITLE
Update/Refactor repeated/existing code 

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#146]
Our code is sometimes hard to read; Alex said we should try to clean it up (less If-statements, etc.)
From the feedback:
- nested ifs are bad. hard to read, hard to maintain. You can avoid many of them by bailing early when there is an error condition.
- use Enum instead of int (ClaimStatus)
- Currency/CurrencyEnum. Why is amount a part of CurrencyEnum?
     - needs to be public, with getters and setters
- And you can see his code examples [here](https://github.com/CMPUT301W15T13/TravelPlanner/wiki/TA-Feedback-Mar-5)
- See also Edwin's refactoring [issue](https://github.com/CMPUT301W15T13/TravelPlanner/issues/140)

**Comment by eorodrig** [comment]
Got rid of nested ifs. (Might need someone else to verify this).

Created ExceptionHandler Class which will check to see if a field is empty, and will throw an EmptyFieldException when the field is empty.

**Comment by eorodrig** [comment]
Currency Class done.

**Comment by eorodrig** [comment]
Changed claimstatus to Enum
Fixed code
