### ISSUE TITLE
Re-evaluate TravelDestination/Description Implementation

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#148]
I think as a group we want someone to be able to go to the same place more than once and give it the same description. We need to account for this.

- Alex's example: Currently our system can't handle leaving edmonton with description "Home", and coming back to Edmonton with description "Home"
From the feedback:
- I can't go to the same place twice on one trip? Eg. Edmonton -> New York -> San Fransisco -> New York -> Edmonton

**Comment by eorodrig** [comment]
fixed this,

We can now have duplicate entries
