### ISSUE TITLE
UI Storyboard Sequence

### ISSUE THREAD

**Issue by jihwan1ua** [CMPUT301W15T13/TravelPlanner#149]
Hey guys, I was just going through the UI Storyboard on wiki but somehow the UI Storyboard Sequence is not visible on this pc.
I'm using PC on CS 2nd floor so I dont think this has anything to do with the pc itself.
Can anyone double check if the UI Storyboard Sequence is visible on wiki?

**Comment by bkhunter** [comment]
It works for me. The problem may be that I made it a super high resolution file, so it is really large...I know the 2nd floor computers don't have much processing power...It's also in the repo, under /docs/Layout and Storyboard - Firefox compatible/Sequence.png, so if you pull that you can open it with an image viewer.

**Comment by bkhunter** [comment]
Also if you want to reduce the size, that's cool

**Comment by jihwan1ua** [comment]
Cool
