### ISSUE TITLE
Claim getDateAsText and getDestinationsAsText methods

### ISSUE THREAD

**Issue by mfritze** [CMPUT301W15T13/TravelPlanner#150]
In the application it would be very useful to have a method in the claim class that converts the Date into a string in a standard way that would be used across the application. The Destinations as text would be helpful for displaying them in the create/edit claim screen. The dates would be useful when displaying the date in the claim manager activity, as well as in the array adapter for each claim. 

I'm making an issue since I have no idea if someone is currently working on that class. They're not long methods, so if by tomorrow/Thursday it's unimplemented I'll just write a quick one.

**Comment by eorodrig** [comment]
What format would you like the string to be?
12-13-2014
13-12-2014
Jan 13,2014
January 13,2014

**Comment by bkhunter** [comment]
I'm a sucker for MM/DD/YYYY, but I'm easy

**Comment by eorodrig** [comment]
MM/DD/YYYY would be nice and easy, but in my opinion (and if space is available), i would suggest either:
Jan 13,2014
January 13,2014

This will make it easier for the user to quickly know which date the claim/expense occured

**Comment by bkhunter** [comment]
True, and it would be less difficult to misinterpret. And I like spelling out the entire month.

**Comment by eorodrig** [comment]
Added the methods

These will return the short Month Names
getStartDateAsString()
getEndDateAsString()

This  will return "Destination : Description \n"   per each travel Itinerary
getTravelItineraryAsString()
