### ISSUE TITLE
Ensure that code conforms to convention

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#151]
Look through code to make sure it's stye matches

**Comment by bkhunter** [comment]
Going through and checking the UML I also looked over most code. It all looks good, apart from what was/will be added. Should just need one final check tomorrow.

**Comment by lolicatgirls** [comment]
Sounds good, Once I sort out code on my end I'll go through it again deleting any temporary code comments and put little blurbs on what methods are doing
