### ISSUE TITLE
UML Question

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#161]
Question: We have 10 controllers, should they all go in the UML?
And also, is it okay to omit getters and setters?

@aewilson-ua

**Comment by aewilson-ua** [comment]
Yes, the controllers should all be in there.  You can omit getters and setters.

**Comment by mfritze** [comment]
Ben, I will also be making a couple new controller classes for the non-view methods in the activities. I'll add those to the UML when I'm finished with them.

**Comment by bkhunter** [comment]
Awesome thanks. And that sounds good Matt, maybe hold off on that for a bit I'm still updating the UML, and I don't know how well git handles dia merges...I'll assign an issue and close it when I'm done

**Comment by bkhunter** [comment]
Also: 
Do we need our activities in the UML?
And I know you said we didn't have to show variables that are implied by aggregation, but what if it's a composition? Do we need to put the data type that holds the implied class instance?

@aewilson-ua

**Comment by aewilson-ua** [comment]
Activities should be in the UML, yes.

As long as you have the aggregation/composition arrows, then that is fine. Include role labels if you feel the relationship needs more clarification (this is a good thing to do in general).

Search for "Associations (relationships between classes)" on http://www.holub.com/goodies/uml/ to see an example of a well-documented relationship.

**Comment by bkhunter** [comment]
Thanks!
