### ISSUE TITLE
Is ClaimID a string or a long

### ISSUE THREAD

**Issue by lolicatgirls** [CMPUT301W15T13/TravelPlanner#163]
It is set up as a long in a lot of methods but in the expenseItem model constructor it is taken as a string
hm hm

**Comment by lolicatgirls** [comment]
From the looks of the models and based on what a UUID is (for when we get to implementing it) 
It looks like it should be a string and declaring it as long in the activities is just a small mistake 

I'm going to assume this for now and refactor some things
let me know what you guys think I'm just going with a logical assumption based on the models

**Comment by bkhunter** [comment]
A UUID is returned as a string

**Comment by eorodrig** [comment]
definitely a string

**Comment by lolicatgirls** [comment]
Sounds good that is what I had assumed, Just need to fix the adapters then

**Comment by lolicatgirls** [comment]
Ah, It was I who was tricked

id in the adapters references the row in the list view not the claim id
oops.
