### ISSUE TITLE
Making it Halfway

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#164]
Hey guys I'm just going through the user stories and I think we can make it to 50% by implementing
the following:
- Incorporating status into claims, ie. not letting a user edit a claim if changes are not allowed, gives us two more basic claim User Stories (+2)
    - also tags are needed for submit functionality (+1)
- Tags. We can't check off the easy "list expense claims" user story until we list the tags as well. Plus if we implement this we should logically finish at least 1 more user story (+2)
- If general Expense Item useability is finished we should be able to check off at least 3 more (ie. delete, view, add) although taking into account claim status (+3).
- Also, if we have photo taking (without viewing, deleting or size checking) that's 1 more (+1)
- looks like we will want the approvers ability to view a claim and details, and add a comment (+3)

Overall that makes 12 + 7 we have already done = 19/39 = 48.7%

**Comment by bkhunter** [comment]
I will make the release plan for PP5 with the rest of the User Stories

**Comment by lolicatgirls** [comment]
Expense Item add is done
Delete should be simple enough and will think about view 

also how did we want to show names while in the expense item viewer 
currently I have it set to show the ClaimsID that we are adding expenses to
and the expenses ID

**Comment by eorodrig** [comment]
I also noticed that a new expense shows up as the UUID? in the expense list.
Would this be an issue we could fix to give us +1?

**Comment by bkhunter** [comment]
list all the expense items for a claim, in order of entry, showing for each expense item: the date the expense was incurred, the category, the textual description, amount spent, unit of currency, whether there is a photographic receipt, and incompleteness indicator.

If we do that it's +1

**Comment by lolicatgirls** [comment]
Yeah right now I have the expenses show as their UUID which is bulky and not very intuitive plus the user probably doesn't care too much about it

I'm thinking of using an expense name instead

**Comment by bkhunter** [comment]
I think that's a good call, plus the user probably knows which claim they're looking at anyway

**Comment by bkhunter** [comment]
Also if we can sort the claims by date that would be another @mfritze

**Comment by eorodrig** [comment]
I think the claim dates are now sorted..

Will work on displaying the fields...when i find the related methods...

**Comment by eorodrig** [comment]
claim list seems to be sorted..
all claim list fields specified by the UI are showing.
total cost is still 0. Will need to add code to to implement this.

**Comment by bkhunter** [comment]
Tested it, I think they may be sorted the wrong way? They should be sorted from most recent to oldest.

**Comment by lolicatgirls** [comment]
date created 
or 
date of the trip

There could be some confusion there

**Comment by bkhunter** [comment]
"sorted by starting date of travel, in order from most recent to oldest"...I guess it is a little vague...as long as we do some sort of sorting lol
