### ISSUE TITLE
Changing Activities to FragmentActivities

### ISSUE THREAD

**Issue by mfritze** [CMPUT301W15T13/TravelPlanner#176]
So I've been looking into Tab/Swipe views more, and in order to get that functionality, it would mean that we would need to change our Activities to FragmentActivities. In terms of functionality, I believe FragmentActivities can do everything Activities can and more. This provides two things, 
* 1. We get swipe views which is (probably) much more intuitive 
* 2. It's a good opportunity to re-factor the messy Activity code, since the FragmentActivity handles changing fragments a lot better.

However, it also means "starting over". I am personally in favour of doing so, and would happily take on the responsibility of making that transition an a new branch that would be merged later. 

What do you guys think?

**Comment by bkhunter** [comment]
I'm not sure. If we have time It would be nice, but I think it depends on how much people are able to work. What does everyone else think?

**Comment by eorodrig** [comment]
It would be a good feature to include, and refactoring is also part of part 5

**Comment by lolicatgirls** [comment]
an interesting idea, Time may become an issue though it may be easier this time around.
