### ISSUE TITLE
Anyone had problem working in the general access lab machine?

### ISSUE THREAD

**Issue by jihwan1ua** [CMPUT301W15T13/TravelPlanner#183]
Hey, I was just working on approver comments for few hours and the lab machine in general access i was working on just froze up and I can't do anything!
Anyone here had same problem in the past or something??
Man I hate to see all my work gone

**Comment by bkhunter** [comment]
you could try logging in on another machine and see if the changes are there?

**Comment by bkhunter** [comment]
I think you can log in at more than one machine....not sure though

**Comment by lolicatgirls** [comment]
The network has been pretty wonky the last couple of weeks, it can take up to 5+ minutes for it to unfreeze in somecases

**Comment by mfritze** [comment]
This is no longer relevant. I hope...
