### ISSUE TITLE
OnClickListener Error

### ISSUE THREAD

**Issue by jihwan1ua** [CMPUT301W15T13/TravelPlanner#186]
In my code I'm writing for approver comment, I'm getting OnClickListener Error and I'm little puzzled about why it is causing the error

Here are my codes for the class ApproverReturnChoiceDialogFragment which implements DialogFragment

This class basically let approver to add comments upon returning a claim

package dialogs;

import ca.ualberta.cmput301w15t13.R;
import ca.ualberta.cmput301w15t13.Fragments.ClaimViewerFragment;
import android.annotation.SuppressLint;
import android.content.DialogInterface.OnClickListener;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.Button;
import android.app.AlertDialog;
import android.app.Dialog;
import android.app.DialogFragment;
import android.app.FragmentManager;
import android.os.Bundle;

public class ApproverReturnChoiceDialogFragment extends DialogFragment {
	/**
	 * when approver click on Cancel, the fragment will stop and return to the claim view
	 * fragment
	 */
	final OnClickListener ReturnToView = new OnClickListener(){
		@Override
		public void onClick(final View v) {
     	   FragmentManager fm = getFragmentManager();
     	   ClaimViewerFragment fragment = (ClaimViewerFragment) fm.findFragmentByTag("ClaimViewer");
     	   fragment.viewClaim();
     	   Dialog d = getDialog();
     	   d.dismiss();
		}

	/**
	 * when approver click on Ok, the fragment will stop and it will move to Approver Comment
	 * Dialog fragment
	 */
	final OnClickListener ToCommentDialog = new OnClickListener() {
        @Override
		public void onClick(final View v) {
      	   FragmentManager fm = getFragmentManager();
      	   ClaimViewerFragment fragment = (ClaimViewerFragment) fm.findFragmentByTag("ClaimViewer");
      	   fragment.viewClaim();
      	   Dialog d = getDialog();
      	   d.dismiss();
        }
    };
	   
    @SuppressLint("InflateParams")
	@Override
	public Dialog onCreateDialog(Bundle savedInstanceState) {
	    AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
	    LayoutInflater inflater = getActivity().getLayoutInflater();
	    View view = inflater.inflate(R.layout.approver_return_choice_dialog, null);

	    builder.setView(view);
	    
	    Button Cancel = (Button) view.findViewById(R.id.ButtonReturnCancel);
	    Button Ok = (Button) view.findViewById(R.id.ButtonReturnOk);
	    
	    // this line will prevent user from clicking anywhere else than two buttons
	    setCancelable(false);
	    
	    Cancel.setOnClickListener(ReturnToView);
	    Ok.setOnClickListener(ToCommentDialog);
	    
	    return builder.create();
	}

}

Can someone guide me where the error is please?

**Comment by jihwan1ua** [comment]
Oh btw the error message is this

The type new DialogInterface.OnClickListener(){} must implement the inherited abstract method DialogInterface.OnClickListener.onClick(DialogInterface, int)

**Comment by jihwan1ua** [comment]
Nevermind, it was simple error

**Comment by aewilson-ua** [comment]
I'm glad you got it figured out!
