### ISSUE TITLE
Code Functionality: edit expense items

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#19]
User story:
[US04.06.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/85)

**Comment by eorodrig** [comment]
This came up when I was implementing some of the expense items.

I added a method to test for this in the singletonclaimlist as well as the claimList. (See expense class for method functionality)

**Comment by jihwan1ua** [comment]
Ok leave it to me!
