### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#194]
Is anyone working on this or shoud I get started on it?

**Comment by bkhunter** [comment]
Update: Had trouble setting it up on the lab machines so I will do something else for now

**Comment by mfritze** [comment]
I can dedicate my day tomorrow to geolocation. I'm working from home, though.

**Comment by bkhunter** [comment]
That could be good. I wanted to use the google API but I couldn't install the GooglePlay package in the labs sdk manager. Hopefully you'll have better luck with it :+1:
