### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#197]
Can we get 3/3 on tests withut UI testing?

 I was looking at the android UI testing page and they say one option is to just have a human test the UI; could we just say we did that? Because we have pretty good test coverage apart from the UI-related user stories.

@aewilson-ua

**Comment by aewilson-ua** [comment]
"Provide JUnit test cases for your model classes and public methods. The tests should generally pass. Deliver the updated test code to your source repository. If you have test data files, also include those. All useCases should be tested. To avoid confusion make it clear if a test is addressing a usecase."

If your models are fully tested and you have tests per use case (you don't need UI automation, just make a test that uses the controllers and models to follow the flow), then I will consider that sufficient.

**Comment by bkhunter** [comment]
I'm a little confused, so for example US01.03.01:
As a claimant, I want to view an expense claim and its details.

Would something like this work?

ClaimList cl = ClaimListSingleton.getClaimList();
Claim claim1 = new Claim("Name", new Date(1), new Date(2), "Desc", new TravelItineraryList());
cl.add(claim1);
assertTrue("Claimlist not populated", cl.size()==1);
assertNotNull("Claimant cannot view details", cl.getClaimAtIndex(0).getUserName());
assertNotNull("Claimant cannot view details", cl.getClaimAtIndex(0).getStartDate());
assertNotNull("Claimant cannot view details",cl.getClaimAtIndex(0).getEndDate());
assertNotNull("Claimant cannot view details",cl.getClaimAtIndex(0).getDescription());
assertNotNull("Claimant cannot view details",cl.getClaimAtIndex(0).getTravelItineraryAsString());

**Comment by aewilson-ua** [comment]
Sure, that looks good. For some of the "I want to view" user stories there will not be much to test, and that's okay.

**Comment by bkhunter** [comment]
Thanks so much!
