### ISSUE TITLE
TagManager saving

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#198]
is the tag manager being saved for the claimlist? It seems like the claim retains its tags when you kill the app, but I can't filter by them, or add them to a new claim with the add existing option.

**Comment by eorodrig** [comment]
Tag manager is not being saved. I will look into it after I resolve the issue with Edit Expense which seems to crash the app

**Comment by bkhunter** [comment]
Sounds good

**Comment by eorodrig** [comment]
The Tag Manager is now "saved".
When loading a claim, the tag manager is simply re-populated with all the tags.
Seems to work pretty well for my tests
