### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#204]
Hey Alex, does the bonus video have to be submitted on Tuesday, or can it be submitted after our live demo? I'm thinking this makes sense because then we can make it as we make the live demo video, and won't have to worry about changing layouts or waiting for features. Although totally understandable if not, just want to clarify.

Thanks

@aewilson-ua

**Comment by aewilson-ua** [comment]
As long as its done by the time you present to the class, that will work.
