### ISSUE TITLE
Receipt tests may have been broken

### ISSUE THREAD

**Issue by lolicatgirls** [CMPUT301W15T13/TravelPlanner#207]
Sorry about that, I will fix them with the new methods soon

**Comment by bkhunter** [comment]
Hopefully just a matter of changing constructors. No rush.

**Comment by lolicatgirls** [comment]
These should be fixed. 
I think the only receipt based test still giving me trouble is the view image one

**Comment by bkhunter** [comment]
All receipt tests pass
