### ISSUE TITLE
ExpenseItem class

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#209]
@lolicatgirls 
Going through the code, there are a Ton of TODOs in the expenseItem class. Have these been done? do they need to be done? will they be done?

@mfritze 
Also there are unused funtions for setting an incompleteness indicator, I assume you took a different approach? 

Go everyone go!

**Comment by mfritze** [comment]
If they're blank, remove them.

**Comment by bkhunter** [comment]
K

**Comment by bkhunter** [comment]
Sorry guys I'm dumb, most of them were implemented just with todo comments still attatched. Will clean up :/
