### ISSUE TITLE
I think I'm having classpath issues after merge for the google play library 

### ISSUE THREAD

**Issue by lolicatgirls** [CMPUT301W15T13/TravelPlanner#213]
It's probably a simple thing to fix, but I am just not seeing it at the moment
I'm on my personal computer so that probably does not help in my case

**Comment by bkhunter** [comment]
What are you not seeing? The classpath or the google play library?

**Comment by mfritze** [comment]
whats the error message? Are you at home?

**Comment by lolicatgirls** [comment]
The classpath is there but in my libraries in build path I do not see the google play library or the basic JRE 
I wind up with just "Unable to get system library" in its place

Instead of spending more time trying to fix this I'm just going to head on out to the university lab
I'm sure the solution is relatively easy, this way will be faster and less time will have to be dedicated to it

**Comment by bkhunter** [comment]
have you imported in google play services from the addittional libraries folder?
