### ISSUE TITLE
Code Functionality: general claim usability

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#22]
- Adding name, dates, expense items etc.
- Upon submission of a claim nothing will happen for milestone 4
- User stories:
[US01.03.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/50)
[US01.02.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/49)
[US01.01.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/48)

**Comment by eorodrig** [comment]
US01.03.01 is a UI test.

US01.01.01 JUnit test to add a claim to a ClaimList object passes. will need to test adding the claim to the singleton class at a later time.
US01.02.01 passes.

**Comment by bkhunter** [comment]
Working on passing claim tests

**Comment by eorodrig** [comment]
Models do not check for User permission per Alex's feedback.
https://github.com/CMPUT301W15T13/TravelPlanner/issues/144

Rolled back the changes made to solve this issue. Will modify tests.
