### ISSUE TITLE
Code Functionality: claims sorted by date and tags

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#35]
User stories:
[US02.01.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/54)
[US02.02.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/55)
[US03.03.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/58)

**Comment by eorodrig** [comment]
US02.02.01 implemented... see issue #25
