### ISSUE TITLE
Number Use Cases

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#44]

**Comment by eorodrig** [comment]
Does anyone know which Section (US) this belongs to?

It's the only Use Case which is not complete or numbered.

### Use Case Name
**Participating Actors**: Claimant   
**Goal**: View a returned or approved claim  
**Trigger**:  
**Pre-condition**:  
**Post-Condition**: 
**Qualities**:  
**Constraints**:  
**Includes**:  
**Extends**:  
**Notes**:  
**Open Issues**:  

**Basic Flow**:  
1.  
2.
