### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#45]
- Remember Alex said to potentially split these up
- Also need pre and post conditions

**Comment by mfritze** [comment]
I'm going to try to write the rest of them up right now.

**Comment by lolicatgirls** [comment]
I created a ton of issues numbered by each use case under project 2 milestones, currently scanning through code and checking off those that we have

**Comment by mfritze** [comment]
Yeah I saw that, it looks good.

Should I say which use cases I'm working on while I write them up then? Is there a differentiation between the use case and the testing for it?

**Comment by lolicatgirls** [comment]
Hm, good question. Maybe just assign yourself to the use cases you're working on, I think it will show up on the issue list

**Comment by lolicatgirls** [comment]
I left a short comment on what I think are View/UI tests or in otherwords not applicable to our deliverables on part  2

I left anything I wasn't sure about alone

**Comment by mfritze** [comment]
In terms of the other fields for Use Cases (like trigger, qualities etc.) do you think we should remove them from our wiki so the layout is cleaner, and their are fewer lines?

**Comment by lolicatgirls** [comment]
If they aren't applicable to case go for it, I'm unsure of how you're doing the naming so feel free to change the case names on entries
