### ISSUE TITLE
Relocating UI/View/Unempirical tests to their own separate milestone?

### ISSUE THREAD

**Issue by lolicatgirls** [CMPUT301W15T13/TravelPlanner#90]
What do you think? Yes/No? 
I can take care of the migration

**Comment by bkhunter** [comment]
If you like you could add a milestone for them, but I think they everything should stay linked to a project milestone as well. Just so we get the progress bar and can organize that way. I think something can have >1 milestones...

**Comment by mfritze** [comment]
Yeah I think this is a good idea so we don't lose track of them. Make a new milestone called like UI tests?

And yeah, I want that progress bar to hit 100 >:)

**Comment by lolicatgirls** [comment]
yeah I'll make a new milestone for this. 

We can relocate these tests to project parts as needed I don't think UI/View type things are required for part 2
